### ISSUE TITLE
Nozzle sends more than 200 time series in a single request

### ISSUE THREAD

**Issue by knyar** [cloudfoundry-community/stackdriver-tools#137]
With nozzle built from `develop` branch and the default `metrics_buffer_size` set to 200 I am seeing the following errors from Stackdriver:

> code = InvalidArgument desc = Field timeSeries had an invalid value: A maximum of 200 TimeSeries can be written in a single request.

I believe this is caused by the fact that `metrics_buffer_size` limits the number of `MetricEvent`s passed to the metric adapter, however each `MetricEvent` can have multiple metrics (which share the same labels). As the result, 200 `MetricEvent`s can result in more than 200 `TimeSeries` in a `CreateTimeSeriesRequest`.

There should probably be a stricter check that ensures that `CreateTimeSeriesRequest` always conforms to API restrictions and does not have more than 200 time series.

**Comment by johnsonj** [comment]
Great catch. I'll take this one.

**Comment by johnsonj** [comment]
The batching should be moved into the MetricAdapter so we can have that stricter check.

**Comment by fluffle** [comment]
Just to add $0.02 here, since you're refactoring this code anyway: IMO the current abstraction provided by MetricEvent is not quite correct, because associating a *list* of {timestamp, value} Metrics with a label set forces you to jump through some otherwise unnecessary hoops.

I think it would be better to skip having nozzle-specific Metric and MetricEvent structs completely and just use stackdriver protos throughout the nozzle, since that's the representation you need to use eventually. Converting to a slightly different internal representation in one place and then converting to the sd representation later adds unnecessary complexity.

**Comment by johnsonj** [comment]
I don't like the complexity and would like to overall simplify this system where possible. We do send `messages.MetricEvent` to Stackdriver Logging so it's not necessarily in the format we _need_ everywhere, but the stackdriver protos would probably do just fine in the log output even if it's a bit noisy. 

You're right that `timestamp` doesn't at all belong in `Metric`. I'm making the following moves:
- move `messages.Metric.EventTime` -> `messages.MetricEvent.Time`
- rename `messages.Metric` -> `messages.DataPoint`

I'll think more on the proto problem. The plus side today is we don't have coupling between the metric processing/ingestion and the proto format of Stackdriver. A nice seam if we need to upgrade API versions. But this is the Stackdriver Nozzle so coupling doesn't seem unwarranted.

**Comment by fluffle** [comment]
From a brief examination I couldn't see where MetricEvent was sent to SD logging, can you give me a link?

I should have been clearer before, I was strictly talking about using SD protos for the metrics side of things. IMO for logging purposes we'd want to mutate the protos coming from the firehose as little as possible. And FWICS that's what you're doing, translating them into a map[string]interface{} that can be marshalled to JSON, and then using that map as the payload.

As for metrics: no, that's not what I was saying -- the timestamp definitely belongs with the value. The way stackdriver models a timeseries is the way we've done it internally since borgmon days: a timeseries is a list of {timestamp, value} points associated with a *single* metric name and a key=>value label set. (In fact the metric "name" was just a label with the name "var" in borgmon days.)  This is pretty much the same model that OpenTSDB and InfluxDB (allows a list of values per timestamp), to name two other TSDBs, use.

Your approach associates  *>1* metric names and {timestamp, value} lists with a label set, which should be ~fine most of the time but caused the problem with batching being incorrect, because for container metrics you were publishing 6 timeseries per MetricEvent. In general I think you're going to run into these sorts of minor impedance mismatches occasionally when you deviate from the data model that your storage medium is using, which is why I propose the move towards using SD protos as consistently as possible for Metrics.

**Comment by johnsonj** [comment]
[Here's where MetricEvent is sent to Stackdriver Logging](https://github.com/cloudfoundry-community/stackdriver-tools/blob/develop/src/stackdriver-nozzle/metrics_pipeline/router.go#L34). 

When I first implemented sending 'Metrics' to Stackdriver Logging I was writing the payload directly from the firehose to Stackdriver Logging. I backed away from that because the frequency is so high (multiple ContainerMetrics/second for a single instance).

The weird case is is when we take in an `events.Envelope` that produces several time series (eg `cpuPercentage`, `memoryBytes`). When we do that, we have a single `MetricEvent` with multiple values but the values all share the same `{labels, timestamp}`

We could change that though. We could treat them all as individual things. Drop `MetricEvent`, `DataPoint` and write out a `monitoring.TimeSeries` for each value [here](https://github.com/cloudfoundry-community/stackdriver-tools/blob/develop/src/stackdriver-nozzle/nozzle/metric_sink.go#L43). I can't think of why not to do it beyond pretty formatting in Stackdriver Logging.
