### ISSUE TITLE
Throttle TimeSeries requests to Stackdriver metrics API

### ISSUE THREAD

**Issue by evandbrown** [cloudfoundry-community/stackdriver-tools#62]
The Stackdriver API recommends sending at most 1 TimeSeries value every 30s (a batch request can contain 200 individual TimeSeries values). The nozzle should keep a map of TimeSeries values and put them to the API at a 30s interval.

**Comment by GarimaSharma** [comment]
We are using Opsman 1.11.6, ERT 1.11.7 and stackerdriver nozzle 1.0.3 
We are facing this issue for our setup as well `rpc error: code = 13 desc = stream terminated by RST_STREAM with error code: 2` in our `/var/vcap/sys/log/stackdriver-nozzle/stackdriver-nozzle.stdout.log` logfile.

We noticed that this was fixed in [1.0.2 version](http://docs.pivotal.io/partners/gcp-sdn/release-notes.html#102)
We are still seeing it in 1.0.3 - is there a configuration setting that we have missed to enable this fix?
