### ISSUE TITLE
Use the gce_instance monitored resource type

### ISSUE THREAD

**Issue by evandbrown** [cloudfoundry-community/stackdriver-tools#63]
Using `gce_instance` instance as the monitored resource type (rather than the `global` monitored resource) increases throughput as nozzle instances are added since the Stackdriver API shards based on the `gce_instance`'s `instance_id` label.

**Comment by johnsonj** [comment]
This has been addressed where it makes sense. The nozzle now records its own metrics sharding on `gce_instance`. The metrics coming out of Cloud Foundry need to stay global so that the calculations aren't messed up. 

This was more relevant before we had robust filtering, grouping of metrics. Now that the nozzle fits in the default metric quota we've greatly reduced the load that inspired this issue.
